controller_joint_names: ['', 'Front_Right_Wheel', 'Front_Left_Wheel', 'Back_Right_Rocker', 'Back_Right_Rear_Wheel', 'Back_Right_Center_Wjeel', 'Back_Left_Rocker', 'Back_Left_Rear_Wheel', 'Back_Left_Center_Wheel', ]
